- .github/workflows/ci.yml
> Add CI for building zfs package

- contrib/truenas/rules
> Switch to production builds for SCALE

- lib/libzfs/libzfs_dataset.c
> (backport for 12.0-U7) fix crash in make_dataset_handle_common

- lib/libspl/include/sys/feature_tests.h
- lib/libspl/os/freebsd/mnttab.c
- lib/libzfs/libzfs_sendrecv.c
- module/os/freebsd/zfs/vdev_file.c
- module/zfs/zfs_vnops.c
Jira: NAS-114125, NAS-114320, NAS-114047
> 12.0-U8 backports

- module/os/freebsd/zfs/zfs_vnops_os.c
On FreeBSD, zfs_lookup returns ENOATTR when failing to look up an xattr,
not ENOENT.  Check for this error as well as ENOENT.
Remove some code duplicated by a mismerge.
When deleting existing xattrs in the alternate compat format, we need
the namespace and name filled in as well.
> FreeBSD: Fix edge cases in xattr compat

- module/os/linux/zfs/zpl_xattr.c
Additional testing has revealed cases where fallback behavior is
incorrect for user xattrs after the removal of the xattr_fallback
property.
Always try fallback if the primary method fails, there is no opt-out.
Ensure the alternate format xattr is cleared with either xattr_compat
setting.
> Linux: Fix xattr_compat fallback behavior

- .github/workflows/checkstyle.yaml
- .github/workflows/zfs-tests-functional.yml
- .github/workflows/zfs-tests-sanity.yml
- .github/workflows/zloop.yml
- cmd/zfs/zfs_main.c
- contrib/truenas/control
- lib/libuutil/libuutil.abi
- lib/libzfs/libzfs.abi
- lib/libzfs_core/libzfs_core.abi
- tests/zfs-tests/cmd/getversion/getversion.c
ZFS send: Fix -V operation for Linux
ZFS send -V sets a per second progress report as process title. For
Linux, this functionality depends on libbsd-dev. Adding this library
fixes the report being printed on stderr. `setproctitle_init` is required
on Linux so that `setproctitle()` can function correctly.
Manually tested the ZFS send operation.
> NAS-115872 / ZFS send: Fix -V operation for Linux

- .github/workflows/checkstyle.yaml
- .github/workflows/zfs-tests-functional.yml
- .github/workflows/zfs-tests-sanity.yml
- .github/workflows/zloop.yml
- cmd/zfs/zfs_main.c
- contrib/truenas/control
- lib/libuutil/libuutil.abi
- lib/libzfs/libzfs.abi
- lib/libzfs_core/libzfs_core.abi
- tests/zfs-tests/cmd/getversion/getversion.c
> Revert "NAS-115872 / 22.02 / ZFS send: Fix -V operation for Linux"

- .github/workflows/checkstyle.yaml
- .github/workflows/zfs-tests-functional.yml
- .github/workflows/zfs-tests-sanity.yml
- .github/workflows/zloop.yml
- cmd/zfs/zfs_main.c
- contrib/truenas/control
- lib/libuutil/libuutil.abi
- lib/libzfs/libzfs.abi
- lib/libzfs_core/libzfs_core.abi
- tests/zfs-tests/cmd/getversion/getversion.c
> Revert "NAS-115872 / ZFS send: Fix -V operation for Linux"

- .github/workflows/checkstyle.yaml
- .github/workflows/zfs-tests-functional.yml
- .github/workflows/zfs-tests-sanity.yml
- .github/workflows/zloop.yml
- cmd/zfs/zfs_main.c
- contrib/truenas/control
- lib/libuutil/libuutil.abi
- lib/libzfs/libzfs.abi
- lib/libzfs_core/libzfs_core.abi
- tests/zfs-tests/cmd/getversion/getversion.c
ZFS send: Fix -V operation for Linux
ZFS send -V sets a per second progress report as process title. For
Linux, this functionality depends on libbsd-dev. Adding this library
fixes the report being printed on stderr. setproctitle_init is required
on Linux so that setproctitle() can function correctly.
> NAS-115872 / 22.12 / ZFS send: Fix -V operation for Linux

- .github/workflows/checkstyle.yaml
- .github/workflows/zfs-tests-functional.yml
- .github/workflows/zfs-tests-sanity.yml
- .github/workflows/zloop.yml
- cmd/zfs/zfs_main.c
- contrib/truenas/control
- lib/libuutil/libuutil.abi
- lib/libzfs/libzfs.abi
- lib/libzfs_core/libzfs_core.abi
- tests/zfs-tests/cmd/getversion/getversion.c
ZFS send: Fix -V operation for Linux
ZFS send -V sets a per second progress report as process title. For
Linux, this functionality depends on libbsd-dev. Adding this library
fixes the report being printed on stderr. setproctitle_init is required
on Linux so that setproctitle() can function correctly.
> NAS-115872 / 22.02 / ZFS send: Fix -V operation for Linux

- .github/workflows/checkstyle.yaml
- .github/workflows/zfs-tests-functional.yml
- .github/workflows/zfs-tests-sanity.yml
- .github/workflows/zloop.yml
Allow concurrent skipping for CI
Currently, the CI run for Pull Requests are skipped only if a successful
Push CI run is found. This implies that Push CI run has to complete before
Pull Request should be opened, otherwise Pull Request CI will also start
in parallel to Push CI run. Since ZFS tests take long time to complete, it
makes sense to allow concurrent skipping for Pull Request CI run.
If upon opening a Pull Request, a Push CI run is already in progress,
concurrent skipping allows to skip Pull Request CI run completely.
'same_content_newer' ensures that atleast one of Push or Pull Request is
run. If a new commit is added after opening a Pull Request or in case of
force push, atleast one of Pull Request or Push CI run will be performed.
Manually tested by creating PRs.
> NAS-114972 / Allow concurrent skipping for CI

- cmd/zed/agents/zfs_mod.c
- cmd/zpool/zpool_vdev.c
- config/Rules.am
- lib/libzfs/libzfs_pool.c
- lib/libzfs/os/linux/libzfs_pool_os.c
- tests/zfs-tests/tests/functional/cli_root/zpool_expand/zpool_expand_005_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zpool_reopen/zpool_reopen_005_pos.ksh
- tests/zfs-tests/tests/functional/fault/auto_offline_001_pos.ksh
- tests/zfs-tests/tests/functional/fault/auto_replace_001_pos.ksh
This is sure to cause test failures.
> wip: ignore wholedisk

- META
- config/kernel-acl.m4
- contrib/debian/changelog
- contrib/truenas/changelog
- include/os/linux/zfs/sys/zpl.h
- module/os/linux/zfs/zpl_xattr.c
- module/zfs/zio.c
> Merge zfs-2.1.9

- .github/workflows/ci.yml
- .github/workflows/zfs-tests-functional.yml
- .github/workflows/zfs-tests-sanity.yml
- contrib/debian/control
- contrib/debian/rules.in
dkms package layout is changed in bookworm and splits into dh-dkms package. Debhelper in Bookworm is updated to use dh-sequence-dkms instead of dkms.
GitHub Actions are updated to use Ubuntu 22.04 instead of Ubuntu 20.04, since dh-sequence-dkms is not available on Ubuntu 20.04.
> Fix OpenZFS build issue for Debian Bookworm

- contrib/debian/changelog
- contrib/truenas/changelog
- module/zfs/dmu_recv.c
- module/zfs/dnode.c
> NAS-123123 / None / zfs-2.1 replication hotfix

- contrib/debian/changelog
- contrib/truenas/changelog
This reverts commit 7468f5dcf63e0bf2ed5c73949d25660539229d91.
> NAS-123123 / None / Revert "Bump changelog for 2.1.12-1"

- META
- module/os/freebsd/zfs/zfs_vnops_os.c
- module/zfs/zfs_vnops.c
Merge after upstream zfs-2.2-release rc3 tag
Through CI.
> Merge after upstream zfs-2.2-release rc3 tag

- cmd/zed/zed.d/Makefile.am
- cmd/zed/zed.d/statechange-slot_off.sh
- cmd/zpool/zpool_main.c
- contrib/debian/openzfs-zfsutils.install
- include/libzfs.h
- include/os/linux/kernel/linux/simd_x86.h
- lib/libzfs/libzfs_mount.c
- man/Makefile.am
- man/man7/zfsprops.7
- man/man8/zpool.8
- module/zfs/dbuf.c
- module/zfs/zil.c
- module/zfs/zio.c
- tests/zfs-tests/tests/functional/block_cloning/block_cloning.kshlib
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_cross_dataset.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_fallback.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_fallback_same_txg.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_partial.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_disabled_copyfilerange.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_ficlone.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_ficlonerange.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_ficlonerange_partial.ksh
Sync with upstream zfs-2.2-release.
Merge zfs-2.2-release into truenas/zfs-2.2-release
- ZFS tests through CI Pipeline
- Sanity Tested Scale Build: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/579/
- Sanity Tested Core Build: https://builds.ixsystems.com/view/Custom/job/TrueNAS%20Custom%20Build/193/
> [2.2] Sync with upstream

- META
- module/os/linux/zfs/qat_compress.c
Sync with upstream RC4 tag.
Scale Build: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/590/
Core Build: https://builds.ixsystems.com/view/Custom/job/TrueNAS%20Custom%20Build/194/
> Sync with Upstream RC4 tag

- META
- cmd/zed/zed.d/Makefile.am
- cmd/zed/zed.d/statechange-slot_off.sh
- cmd/zpool/zpool_main.c
- contrib/debian/openzfs-zfsutils.install
- include/libzfs.h
- include/os/linux/kernel/linux/simd_x86.h
- lib/libzfs/libzfs_mount.c
- man/Makefile.am
- man/man7/zfsprops.7
- man/man8/zpool.8
- module/os/linux/zfs/qat_compress.c
- module/zfs/dbuf.c
- module/zfs/zfs_vnops.c
- module/zfs/zil.c
- module/zfs/zio.c
- tests/zfs-tests/tests/functional/block_cloning/block_cloning.kshlib
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_cross_dataset.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_fallback.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_fallback_same_txg.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_copyfilerange_partial.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_disabled_copyfilerange.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_ficlone.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_ficlonerange.ksh
- tests/zfs-tests/tests/functional/block_cloning/block_cloning_ficlonerange_partial.ksh
sync release/23.10-RC.1 with stable/cobia.
> sync release/23.10-RC.1 with stable/cobia

- .github/workflows/docker_image.yml
I need this to build https://github.com/truenas/py-libzfs/pull/251
> NAS-126025 / 24.04 / Update docker_image.yml

- .gitignore
- Dockerfile
> Add Dockerfile

- Dockerfile
Forgot to `git add` something in the previous PR.
> NAS-126767 / None / Change `Dockerfile` to use standard build process
