- contrib/truenas/rules
This PR should only be merged after truenas-build has been updated for custom kernel builds.
> Build with truenas custom kernel

- module/os/linux/zfs/zfs_vfsops.c
SB_LARGEXATTR is used in TrueNAS SCALE to indicate to the kernel
that the filesystem supports large-size xattrs (greater than 64KiB).
This flag is used to evaluate whether to allow large xattr read
or write requests (up to 2 MiB).
> Set SB_LARGEXATTR if xattr is enabled and kernel supports it

- .gitignore
- Makefile.am
- include/os/linux/spl/rpc/xdr.h
- include/os/linux/zfs/sys/zpl.h
- module/Makefile.in
- module/os/linux/zfs/Makefile.in
- module/os/linux/zfs/nfs41acl.x
- module/os/linux/zfs/policy.c
- module/os/linux/zfs/zfs_vfsops.c
- module/os/linux/zfs/zpl_inode.c
- module/os/linux/zfs/zpl_super.c
- module/os/linux/zfs/zpl_xattr.c
This implements NFSv41 (RFC 5661) ACLs in a manner
compatible with vfs_nfs4acl_xattr in Samba and
nfs4xdr-acl-tools.
There are three key areas of change in this commit:
1) NFSv4 ACL management through system.nfs4_acl_xdr xattr.
Install an xattr handler for "system.nfs4_acl_xdr" that
presents an xattr containing full NFSv41 ACL structures
generated through rpcgen using specification from the Samba
project. This xattr is used by userspace programs to read and
set permissions.
2) add an i_op->permissions endpoint: zpl_permissions(). This
is used by the VFS in Linux to determine whether to allow /
deny an operation. Wherever possible, we try to avoid having
to call zfs_access(). If kernel has NFSv4 patch for VFS, then
perform more complete check of avaiable access mask.
3) add …
> Implement NFSv41 ACLs through xattr

- .github/workflows/docker_image.yml
Update docker image tag for 2.0 branch as using latest for both 2.1/2.0 will cause issues for consumers of the docker image as they can't reliably say when the tag is going to point to 2.0 or 2.1.
> Update docker image tag for 2.0 zfs updates

- cmd/zed/agents/zfs_mod.c
- cmd/zed/zed_disk_event.c
This enables ZED to auto-online vdevs that are not wholedisk managed by ZFS.
> ZED: Match added disk by pool/vdev GUID if found

- cmd/zed/agents/zfs_mod.c
- cmd/zed/zed_disk_event.c
This enables ZED to auto-online vdevs that are not wholedisk managed by ZFS.
> 21.06 / ZED: Match added disk by pool/vdev GUID if found

- man/man7/zfsprops.7
- module/zcommon/zfs_prop.c
- tests/zfs-tests/tests/functional/channel_program/synctask_core/tst.get_index_props.zcp
- tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_001_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_002_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_005_neg.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_008_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_get/zfs_get_009_pos.ksh
- tests/zfs-tests/tests/functional/inheritance/inherit_001_pos.ksh
Now that we support NFSv4 ACLs on Linux, this can now be made the
default across all platforms.
Update the documentation and tests accordingly.
Jira: NAS-111571
> Make acltype=nfsv4 the default on Linux, too

- configure.ac
- include/os/linux/zfs/sys/zfs_znode_impl.h
- module/os/linux/zfs/zfs_znode.c
- module/os/linux/zfs/zpl_inode.c
- tests/runfiles/common.run
- tests/test-runner/bin/zts-report.py.in
- tests/zfs-tests/include/libtest.shlib
- tests/zfs-tests/tests/functional/Makefile.am
- tests/zfs-tests/tests/functional/cli_root/zfs_diff/zfs_diff_timestamp.ksh
- tests/zfs-tests/tests/functional/crtime/Makefile.am
- tests/zfs-tests/tests/functional/crtime/cleanup.ksh
- tests/zfs-tests/tests/functional/crtime/crtime_001_pos.ksh
- tests/zfs-tests/tests/functional/crtime/setup.ksh
https://github.com/openzfs/zfs/pull/12432
Jira: NAS-109929
> NAS-109929: 21.08: Linux 4.11 compat: statx support

- contrib/initramfs/scripts/zfs
The new sysfs attribute makes kernel to wait for all device probe to
complete before return.  Without it wait_for_udev call does not give
any guaranties.
Ticket:	NAS-108200
> Write /sys/kernel/wait_for_device_probe before import.

- lib/libzfs/libzfs_sendrecv.c
- tests/zfs-tests/tests/functional/rsend/rsend_016_neg.ksh
zfs send -R -i snap1 pool/ds@snap1 is an invalid invocation of zfs send
because the incremental source and target snapshots are the same.  We
have an error message for this condition, but we don't make it there
because of a failed assert while iterating through the dataset's
snapshots.
Check for NULL to avoid the assert so we can make it to the error
message.
Test this form of invalid send invocation in rsend tests.  Fix the
rsend_016_neg test while here: log_neg itself doesn't fail the test,
and writing to /dev/null is not supported on all Linux kernels.
> NAS-111618: Fail invalid incremental recursive send gracefully

- module/os/linux/zfs/policy.c
- module/os/linux/zfs/zpl_xattr.c
Properly evaluate edge cases where user credential may grant
capability to override DAC in various situations. Switch to
using ns-aware checks rather than capable().
Expand optimization allow bypass of zfs_zaccess() in case of
trivial ACL if MAY_OPEN is included in requested mask. This
will be evaluated in generic_permission() check, which is
RCU walk safe. This means that in most cases evaluating
permissions on boot volume with NFSv4 ACLs will follow the
fast path on checking inode permissions.
> Fix access check when cred allows override of ACL

- lib/libzfs/libzfs_dataset.c
Running the zettarepl integration tests on TrueNAS will produce core
dumps for the middlewared process 100% of the time.
Crash is occurring in `make_dataset_handle_common` because `zfs_type` is
`DMU_OST_NONE`. Unfortunately, I haven't been successful in tracking
down whether or not this is a valid `zfs_type`. However, 100% of the
crashes that I've investigated from end-users as well as the ones that
were generated by the zettarepl integration tests show that
`dds_inconsistent` is 1. This means the filesystem is in the process of
being received or some case of destruction.
This changes `make_dataset_handle_common` to gracefully handle the
situation when `dds_inconsistent` != 0 and simply return -1 as to not
cause an `abort()`. Investigation has shown that other parts of the libzfs
API also …
> fix abort in make_dataset_handle_common

- man/man5/zfs-module-parameters.5
- module/zfs/arc.c
On FreeBSD vnode reclamation is single-threaded, protected by single
global lock.  Linux seems to be able to use a thread per mount point,
but at this time it creates more harm than good.
Reduce number of threads to 1, adding tunable in case somebody wants
to try more.
> (12) Reduce number of arc_prune threads.

- man/man4/zfs.4
- module/zfs/arc.c
On FreeBSD vnode reclamation is single-threaded, protected by single
global lock.  Linux seems to be able to use a thread per mount point,
but at this time it creates more harm than good.
Reduce number of threads to 1, adding tunable in case somebody wants
to try more.
> (13/SCALE) Reduce number of arc_prune threads.

- module/os/freebsd/zfs/zvol_os.c
Some first open locking changes were applied correctly in zvol_cdev_open
but incorrectly in zvol_geom_open.
> FreeBSD: Fix zvol_geom_open locking

- module/os/linux/spl/spl-cred.c
- module/os/linux/zfs/policy.c
For Linux NFS kernel server ops, fsuid and fsgid in
cred are populated with ids that operation is
being performed as, but euid and egid remain 0.
In Linux when setresuid(2) and setresgid(2) are
called, the fsuid and fsgid are set to the euid
and egid respectively.
This PR changes ZFS ACL checks to evaluate
fsuid / fsgid rather than euid / egid to avoid
accidentally granting elevated permissions to
NFS clients.
Additionally, CAP_SYS_ADMIN is granted to nfsd
process, and so override for this capability in
access2 policy check is removed in favor of
simple check for fsid == 0. Checks for
CAP_DAC_OVERRIDE and other override capabilities
are kept as-is.
> NAS-114734 / Fix ACL checks for NFS kernel server

- module/os/linux/spl/spl-cred.c
- module/os/linux/zfs/policy.c
For Linux NFS kernel server ops, fsuid and fsgid in
cred are populated with ids that operation is
being performed as, but euid and egid remain 0.
In Linux when setresuid(2) and setresgid(2) are
called, the fsuid and fsgid are set to the euid
and egid respectively.
This PR changes ZFS ACL checks to evaluate
fsuid / fsgid rather than euid / egid to avoid
accidentally granting elevated permissions to
NFS clients.
Additionally, CAP_SYS_ADMIN is granted to nfsd
process, and so override for this capability in
access2 policy check is removed in favor of
simple check for fsid == 0. Checks for
CAP_DAC_OVERRIDE and other override capabilities
are kept as-is.
> Fix ACL checks for NFS kernel server (#40)

- include/os/freebsd/zfs/sys/zfs_vfsops_os.h
- include/os/linux/zfs/sys/zfs_vfsops_os.h
- include/sys/fs/zfs.h
- lib/libzfs/libzfs.abi
- man/man4/zfs.4
- man/man7/zfsprops.7
- module/os/freebsd/zfs/zfs_vfsops.c
- module/os/freebsd/zfs/zfs_vnops_os.c
- module/os/linux/zfs/zfs_vfsops.c
- module/os/linux/zfs/zpl_xattr.c
- module/zcommon/zfs_prop.c
- tests/zfs-tests/include/properties.shlib
- tests/zfs-tests/include/tunables.cfg
- tests/zfs-tests/tests/functional/xattr/Makefile.am
- tests/zfs-tests/tests/functional/xattr/xattr_compat.ksh
Upstream review has pushed away from having xattr_compat as a property.
Remove the property and make it a tunable instead.  Also add the test
changes from the upstream PR.
Jira: NAS-114773
> NAS-114773 / Make xattr_compat a tunable, zfs_xattr_compat

- lib/libzfs/libzfs_dataset.c
When a dataset is in the process of being received it gets marked as
inconsistent and should not be used.  We should check for this when
opening a dataset handle in libzfs and return with an appropriate error
set, rather than hitting an abort because of the incomplete data.
zfs_open() passes errno to zfs_standard_error() after observing
make_dataset_handle() fail, which ends up aborting if errno is 0.
Set errno before returning where we know it has not been set already.
Signed-off-by: Ryan Moeller <freqlabs@FreeBSD.org>
Closes #13077
> libzfs: Fail making a dataset handle gracefully

- include/sys/fs/zfs.h
- module/zfs/spa.c
Use error thresholds from policy to control whether to scrub data
and/or metadata.  If threshold is set to UINT64_MAX, then caller
probably does not care about result and we may skip that part.
By default import neither set the data error threshold nor read
the error counter, so skip the data scrub for faster import.
Metadata are still scrubbed and fail if even single error found.
While there just for symmetry return number of metadata errors in
case threshold is not set to zero and we haven't reached it.
Reviewed-by: Pavel Zakharov <pavel.zakharov@delphix.com>
Signed-off-by: Alexander Motin <mav@FreeBSD.org>
Closes #13022
(cherry picked from commit f2c5bc150e609a78185ea63c84fce7718f56e28a)
> NAS-113231 / Add more control/visibility to spa_load_verify().

- lib/libzfs/libzfs_mount.c
- lib/libzfs/libzfs_sendrecv.c
Three general bug fixes in libzfs sendrecv:
https://jira.ixsystems.com/browse/NAS-111548
https://jira.ixsystems.com/browse/NAS-111550
https://jira.ixsystems.com/browse/NAS-111551
And I grabbed a leak fix I spotted nearby since we have had issues in libzfs mount handling recently.
> libzfs sendrecv/mount bug fixes

- lib/libzfs/libzfs_pool.c
The path passed may in fact be a guid, so we want to use the fullpath we
looked up from the pool config instead. But, this causes tests to fail
on Linux so we only do it for FreeBSD.
Jira: https://jira.ixsystems.com/browse/NAS-111553
> FreeBSD: Fix zfsd auto online

- configure.ac
- include/sys/fs/zfs.h
- include/sys/zfs_znode.h
- module/os/linux/zfs/zpl_file.c
- tests/runfiles/common.run
- tests/runfiles/freebsd.run
- tests/runfiles/linux.run
- tests/zfs-tests/cmd/Makefile.am
- tests/zfs-tests/cmd/read_dos_attributes/.gitignore
- tests/zfs-tests/cmd/read_dos_attributes/Makefile.am
- tests/zfs-tests/cmd/read_dos_attributes/read_dos_attributes.c
- tests/zfs-tests/cmd/write_dos_attributes/.gitignore
- tests/zfs-tests/cmd/write_dos_attributes/Makefile.am
- tests/zfs-tests/cmd/write_dos_attributes/write_dos_attributes.c
- tests/zfs-tests/include/commands.cfg
- tests/zfs-tests/tests/functional/Makefile.am
- tests/zfs-tests/tests/functional/acl/off/Makefile.am
- tests/zfs-tests/tests/functional/acl/off/dosmode.ksh
- tests/zfs-tests/tests/functional/acl/off/dosmode_readonly_write.c
- tests/zfs-tests/tests/functional/dos_attributes/Makefile.am
- tests/zfs-tests/tests/functional/dos_attributes/cleanup.ksh
- tests/zfs-tests/tests/functional/dos_attributes/read_dos_attrs_001.ksh
- tests/zfs-tests/tests/functional/dos_attributes/setup.ksh
- tests/zfs-tests/tests/functional/dos_attributes/write_dos_attrs_001.ksh
Provide access to additional file level attributes  on Linux.
FreeBSD already provides access to these attributes.
ZFS allows to update and retrieve additional file level attributes for
FreeBSD. This commit allows additional file level attributes to be
updated and retrieved for Linux. These include the flags stored in the
upper half of z_pflags only.
Two new IOCTLs have been added for this purpose. ZFS_IOC_GETDOSFLAGS
can be used to retieve the attributes, while ZFS_IOC_SETDOSFLAGS can
be used to update the attributes.
Attributes that are allowed to be updated include ZFS_IMMUTABLE,
ZFS_APPENDONLY, ZFS_NOUNLINK, ZFS_ARCHIVE, ZFS_NODUMP, ZFS_SYSTEM,
ZFS_HIDDEN, ZFS_READONLY, ZFS_REPARSE, ZFS_OFFLINE and ZFS_SPARSE.
Flags can be or'd together while calling ZFS_IOC_SETDOSFLAGS.
Two C …
> Expose additional file level attributes

- module/os/linux/zfs/zfs_acl.c
- module/os/linux/zfs/zfs_vnops_os.c
Bypass check of ZFS aces if the ACL is trivial. When an ACL is
trivial its permissions are represented by the mode without any
loss of information. In this case, it is safe to convert the
access request into equivalent mode and then pass desired mask
and inode to generic_permission(). This has the added benefit
of also checking whether entries in a POSIX ACL on the file grant
the desired access.
This commit also skips the ACL check on looking up the xattr dir
since such restrictions don't exist in Linux kernel and it makes
xattr lookup behavior inconsistent between SA and file-based
xattrs. We also don't want to perform a POSIX ACL check while
looking up the POSIX ACL if for some reason it is located in
the xattr dir rather than an SA.
> NAS-115346 / Linux optimize access checks when ACL is trivial

- include/sys/spa.h
- module/zfs/spa_stats.c
There are times when end-users may wish to have
a fast and convenient method to get zpool guid
without having to use libzfs. This commit
exposes the zpool guid via kstats in similar
manner to the zpool state.
Closes #13466
> Expose zpool guids through kstats (#68)

- module/Makefile.bsd
Quick and dirty build fix for warnings being treated as errors.
Signed-off-by: Ryan Moeller <ryan@iXsystems.com>
> FreeBSD: Silence clang unused-but-set-variable

- module/os/linux/zfs/zpl_ctldir.c
Increase nlinks in stat results of ./zfs/snapshot based on snapshot
count. This provides quick and efficient method for administrators to
get snapshot counts without having to use libzfs or list the snapdir
contents.
Reviewed-by: Ryan Moeller <ryan@iXsystems.com>
Closes #13559
> NAS-116769 / expose snapshot count via stat(2) of .zfs/snapshot (#13559)

- module/os/linux/zfs/zpl_ctldir.c
Increase nlinks in stat results of ./zfs/snapshot based on snapshot
count. This provides quick and efficient method for administrators to
get snapshot counts without having to use libzfs or list the snapdir
contents.
Reviewed-by: Ryan Moeller <ryan@iXsystems.com>
Closes #13559
> expose snapshot count via stat(2) of .zfs/snapshot

- module/os/linux/zfs/zfs_vnops_os.c
When a new file is created on FreeBSD it is given the group
of the directory which contains it. On Linux it is given
to either the effective GID of the process (System V semantices)
or the GID of the parent directory (BSD semantics).
Since there is no hard-and-fast rule about creation semantics
for NFSv4 ACLs on Linux, we should opt for what is least likely
to break users permissions on change from FreeBSD to Linux.
Avoid setting actually setting the SGID bit on dirs unless
it was explicitly set.
> NAS-116836 / Force BSD semantics for group ownership if NFSV4ACL

- contrib/initramfs/scripts/local-top/zfs
TrueNAS SCALE doesn't boot from pools on top of LVM, and the scan can
take a significant amount of time on systems with a large number of
disks.
Skip the lvm commands in our local-top/zfs script.
> initramfs: Skip lvm scan before boot pool import

- include/sys/mntent.h
- lib/libzfs/os/linux/libzfs_mount_os.c
- module/os/linux/zfs/zpl_super.c
Expose ZFS dataset case sensitivity setting via sb_opts
Openzfs PR Link: https://github.com/openzfs/zfs/pull/13607
Through following commands:
``` cat /proc/mounts  | grep case``` 
``` mount  | grep case```
> Expose ZFS dataset case sensitivity setting via sb_opts

- cmd/zfs/zfs_iter.c
- cmd/zfs/zfs_iter.h
- cmd/zfs/zfs_main.c
- lib/libzfs/libzfs_dataset.c
- module/zfs/zfs_ioctl.c
Add support for createtxg sort for simple snapshot iterator
When iterating snapshots with name only, e.g., "-o name -s name", libzfs uses simple snapshot iterator and results are displayed in alphabetic order. This PR adds support for faster version of createtxg sort by avoiding nvlist parsing for properties. Flags "-o name -s createtxg" will enable createtxg sort while using simple snapshot iterator.
For 10,000 snapshots, following are the results:
``` 
time zfs list -t snapshot -o name -s createtxg  => 0m1.166s
time zfs list -t snapshot -o name -s name       => 0m1.245s
time zfs list -t snapshot -s createtxg          => 0m3.972s
```
Openzfs PR: https://github.com/openzfs/zfs/pull/13577
Created multiple snapshots for different datasets and verified that they are sorted w.r.t createtxg by …
> Add createtxg sort support for simple snapshot iterator

- include/sys/dsl_dir.h
- include/sys/fs/zfs.h
- lib/libzfs/libzfs.abi
- lib/libzfs/libzfs_dataset.c
- man/man7/zfsprops.7
- module/zcommon/zfs_prop.c
- module/zfs/dsl_dataset.c
- module/zfs/dsl_dir.c
- module/zfs/zcp_get.c
- tests/runfiles/common.run
- tests/runfiles/sanity.run
- tests/zfs-tests/include/libtest.shlib
- tests/zfs-tests/tests/functional/snapshot/Makefile.am
- tests/zfs-tests/tests/functional/snapshot/snapshot_018_pos.ksh
Add `snapshots_changed` as property
Make `dd_snap_cmtime` persistent across mount and unmount
operations by storing in ZAP and restore the value from ZAP on
hold into `dd_snap_cmtime` instead of updating it.
Expose `dd_snap_cmtime` as `snapshots_changed` property
that provides a mechanism to quickly determine whether
snapshot list for dataset has changed without having to mount a
dataset or iterate the snapshot list.
This is an optimization to avoid having to iterate the snapshot list
through ioctl interface and comparing the change. For datasets
with large number of snapshots, iterating the snapshot list tends
to be slower. Comparing the `snapshots_changed` timestamp
provides an alternate and faster mechanism for this.
`snapshots_changed` specifies the time at which a snapshot for
a …
> Add snapshots_changed as property

- include/sys/dsl_dir.h
- include/sys/fs/zfs.h
- lib/libzfs/libzfs.abi
- lib/libzfs/libzfs_dataset.c
- man/man7/zfsprops.7
- module/zcommon/zfs_prop.c
- module/zfs/dsl_dataset.c
- module/zfs/dsl_dir.c
- module/zfs/zcp_get.c
- tests/runfiles/common.run
- tests/runfiles/sanity.run
- tests/zfs-tests/include/libtest.shlib
- tests/zfs-tests/tests/functional/snapshot/Makefile.am
- tests/zfs-tests/tests/functional/snapshot/snapshot_018_pos.ksh
Due to a regression, we had to revert the `snapshots_changed` property, since it reported 
source=local. The fix for this has been merged upstream.
This PR enables `snapshots_changed` property and the fix for source=local is also included.
We now store the property in `dd_object` instead of `dd_props_zapobj`, which reports source
to be `-` instead of `local`.
Manually tested and ran `snapshot_018_pos.ksh`.
Built a TrueNAS SCALE image with this change set and verified property works correctly.
> Re-enable snapshots_changed property

- include/sys/dsl_dir.h
- module/zfs/dsl_dir.c
In dsl_dir zap object, the key/name should be in a format `<reverse-dns>:<field>`. This
was accidentally dropped from previous PR https://github.com/truenas/zfs/pull/93.
This commit adds DD_FIELD string used in extensified dsl_dir zap object for
snapshots_changed property to make it consistent with other properties stored in
dsl_dir zap object.
> Add DD_FIELD string for snapshots_changed property

- cmd/zed/agents/zfs_agents.c
- cmd/zed/agents/zfs_retire.c
- cmd/ztest/ztest.c
- config/kernel-blkdev.m4
- include/libzfs.h
- include/os/linux/kernel/linux/blkdev_compat.h
- include/os/linux/spl/sys/Makefile.am
- include/os/linux/spl/sys/misc.h
- include/sys/spa.h
- include/sys/vdev.h
- include/sys/vdev_impl.h
- include/sys/zfs_context.h
- lib/libzfs/libzfs.abi
- lib/libzfs/libzfs_pool.c
- module/os/linux/spl/spl-generic.c
- module/os/linux/zfs/vdev_disk.c
- module/zfs/spa.c
- module/zfs/spa_config.c
- module/zfs/spa_misc.c
- module/zfs/vdev.c
- module/zfs/zfs_ioctl.c
- module/zfs/zio.c
- tests/zfs-tests/include/libtest.shlib
- tests/zfs-tests/tests/functional/fault/auto_offline_001_pos.ksh
zed: mark disks as REMOVED when they are removed
ZED does not take any action for disk removal events if there is no spare VDEV
available.Added ```zpool_vdev_remove_wanted()``` in libzfs and ```vdev_remove_wanted()```
in ```vdev.c``` to remove the VDEV through ZED on removal event.  This means that if
you are running zed and remove a disk, it will be properly marked as REMOVED.
Upstream PR: https://github.com/openzfs/zfs/pull/13797 (Merged)
By hotplugging vdevs through QEMU
> zed: mark disks as REMOVED when they are removed

- cmd/zdb/zdb.c
- cmd/zhack/zhack.c
- cmd/zpool/zpool_main.c
- cmd/ztest/ztest.c
- include/libzutil.h
- lib/libzfs_core/libzfs_core.abi
- lib/libzutil/zutil_import.c
- lib/libzutil/zutil_import.h
In `libzutil`, for `zpool_search_import` and `zpool_find_config`, we use `libpc_handle_t`
internally, which does not maintain error code and it is not exposed in the interface.
Due to this, the error information is not propagated to the caller. Instead, an error
message is printed on stderr.
This commit adds `lpc_error` field in `libpc_handle_t` and exposes the handle in the
interface, which can be used by the users of `libzutil` to get the appropriate error
information and handle it accordingly.
Users of the API can also control if they want to print the error message on stderr.
> Expose libzutil error info in libpc_handle_t

- contrib/truenas/rules
Build ZFS packages with debug symbols for SCALE
With --enable-debuginfo configured, ZFS packages are built with debug symbols embedded into the binaries.
Built a SCALE image with this change and confirmed that all kernel modules, userland utilities and libraries have debug symbols.
> Build ZFS packages with debug symbols

- cmd/zed/agents/zfs_mod.c
zed aborts and dumps core in vdev_whole_disk_from_config() if the wholedisk property does not exist. make_leaf_vdev() adds the property but there may be already pools that don't have the wholedisk in the label.
OpenZFS PR: https://github.com/openzfs/zfs/pull/14062
By creating pools through [py-libzfs](https://github.com/truenas/py-libzfs) that did not populate the wholedisk parameter previously.
> zed: Avoid core dump if wholedisk property does not exist

- module/zfs/spa_misc.c
zed: post a udev change event from spa_vdev_attach()
In order for zed to process the removal event correctly, udev change event needs to be posted to sync the blkid information. ```spa_create()``` and ```spa_config_update()``` posts the event already through ```spa_write_cachefile()```. Doing the same for ```spa_vdev_attach()``` that handles the case for vdev attachment and replacement.
By hotplugging emulated drives through QEMU and with real drives
> zed: post a udev change event from spa_vdev_attach()

- module/os/linux/zfs/zfs_acl.c
zfs_zaccess_trivial() calls the generic_permission() to read xattr attributes. This may cause a deadlock if the xattr and dent locks are already held. This commit adds a workaround to skip permission checks for the POSIX ACL type.
**Upstream Fix (In progress)**: https://github.com/openzfs/zfs/pull/14220
```
USER_NON_ROOT=$USER
truncate -s 1G /tmp/f1
zpool create tank /tmp/f1 -f
zfs create -o xattr=dir -o acltype=posix -o mountpoint=/data tank/data
echo "TEMP" > /data/file1
chown $USER_NON_ROOT:$USER_NON_ROOT /data/file1
setfacl -m u:$USER_NON_ROOT:rwx /data/file1
```
> Skip permission checks for POSIX ACL type

- contrib/initramfs/scripts/zfs
Legacy mountpoint datasets should not pass `-o zfsutil` to `mount.zfs`. Fix the logic in `mount_fs()` to not forget we have a legacy mountpoint when checking for an `org.zol:mountpoint` userprop.
https://ixsystems.atlassian.net/browse/NAS-119294
> initramfs: Fix legacy mountpoint rootfs (bluefin)

- module/os/linux/zfs/zfs_acl.c
- module/os/linux/zfs/zfs_dir.c
- module/os/linux/zfs/zfs_vnops_os.c
- module/os/linux/zfs/zpl_xattr.c
- tests/zfs-tests/tests/functional/acl/posix/posix_004_pos.ksh
```zfs_zaccess_trivial()``` calls the ```generic_permission()``` to read xattr attributes. This causes deadlock if called from ```zpl_xattr_set_dir()``` context as xattr and the dent locks are already held in this scenario. This commit skips the permissions checks for extended attributes since the Linux VFS stack already checks it before passing us the control.
Upstream PR: https://github.com/openzfs/zfs/pull/14220
Without this patch, ```setfacl``` would be deadlocked:
```
USER_NON_ROOT=$USER
truncate -s 1G /tmp/f1
zpool create tank /tmp/f1 -f
zfs create -o xattr=dir -o acltype=posix -o mountpoint=/data tank/data
echo "TEMP" > /data/file1
chown $USER_NON_ROOT:$USER_NON_ROOT /data/file1
setfacl -m u:$USER_NON_ROOT:rwx /data/file1
```
> [truenas/zfs-2.1-release] skip permission checks for extended attributes

- module/os/linux/zfs/zfs_acl.c
- module/os/linux/zfs/zfs_vnops_os.c
MS-FSCC 2.6 is the governing document for
DOS attribute behavior. It specifies the following:
For a file, applications can read the file but
cannot write to it or delete it. For a directory,
applications cannot delete it, but applications can create and delete files from the directory.
> NAS-120099 / Fix ZFS_READONLY implementation on Linux

- module/os/linux/zfs/zfs_acl.c
- module/os/linux/zfs/zfs_vnops_os.c
MS-FSCC 2.6 is the governing document for
DOS attribute behavior. It specifies the following:
For a file, applications can read the file but
cannot write to it or delete it. For a directory,
applications cannot delete it, but applications can
create and delete files from the directory.
> Fix ZFS_READONLY implementation on Linux (#121)

- include/sys/spa.h
- module/zfs/spa.c
- module/zfs/vdev.c
Spare vdev should detach from the pool when a disk is reinserted. However, spare detachment depends on the completion of resilvering, and if resilver does not schedule, the spare vdev keeps attached to the pool until the next resilvering. When a zfs pool contains several disks (25+ mirror), resilvering does not always happen when a disk is reinserted. In this patch, spare vdev is manually detached from the pool when resilvering does not occur and it has been tested on both Linux and FreeBSD.
Signed-off-by: Ameer Hamza <ahamza@ixsystems.com>
Closes #14722
Created a pool with 25 data mirrors and two spare vdevs. Detached and reattached several data disks to verify spare detaches when the disk …
> [truenas/zfs-2.1-release] Fix "Detach spare vdev in case if resilvering does not happen"

- module/os/linux/zfs/zpl_xattr.c
This function can be frequently called with MAY_EXEC|MAY_NOT_BLOCK during RCU path walk. Where possible we should try not to break out of it. In this case we check whether flag ZFS_NO_EXECS_DENIED is set and check mode (similar to fastexecute check in zfs_acl.c).
> NAS-121765 / Improve zpl_permission performance

- module/os/linux/zfs/zpl_xattr.c
This function can be frequently called with MAY_EXEC|MAY_NOT_BLOCK during RCU path walk. Where possible we should try not to break out of it. In this case we check whether flag ZFS_NO_EXECS_DENIED is set and check mode (similar to fastexecute check in zfs_acl.c).
> Improve zpl_permission performance

- module/zfs/spa.c
- tests/runfiles/common.run
- tests/zfs-tests/tests/functional/cli_root/zpool_import/Makefile.am
- tests/zfs-tests/tests/functional/cli_root/zpool_import/import_log_missing.ksh
spa_import() relies on a pool config fetched by spa_try_import() for spare/cache devices. Import flags are not passed to spa_tryimport(), which makes it return early due to a missing log device and missing retrieving the cache device and spare eventually. Passing ZFS_IMPORT_MISSING_LOG to spa_tryimport() makes it fetch the correct configuration regardless of the missing log device.
Signed-off-by: Ameer Hamza <ahamza@ixsystems.com>
Closes #14794
> zpool import -m also removing spare and cache when log device is missing

- module/os/freebsd/zfs/zvol_os.c
Protect zvol_cdev_read with zv_suspend_lock to prevent concurrent release of the dnode, avoiding panic when a snapshot is rolled back in parallel during ongoing zvol read operation.
Closes: https://github.com/openzfs/zfs/pull/14839
In FreeBSD, when a zvol read operation is in progress, a snapshot rollback can lead to a panic if the volmode is set to dev. To prevent the panic, we protect the zvol_cdev_read function with the zv_suspend_lock. This ensures that the dnode is not concurrently released, thereby avoiding the panic.
Tested through following commands in FreeBSD with zfs volmode set to dev.
```
truncate -s 8G /f1
zpool create -f tank /f1
zfs create -V 4G tank/zv1
zfs snapshot tank/zv1@sp1
dd if=/dev/urandom of=/dev/zvol/tank/zv1 bs=512 count=1M status=progress
zfs rollback -r …
```
> [truenas/zfs-2.1-release] Prevent panic during concurrent snapshot rollback and zvol read

- include/os/linux/zfs/sys/zpl.h
- module/os/linux/zfs/policy.c
- module/os/linux/zfs/zpl_xattr.c
The CI workflow was no longer compiling successfully after its container recently moved to Linux 6.3. This patch adds compatibility support for Linux kernel 6.3 for the truenas zfs-2.2 branch.
By testing build on 5.15, 6.1, and 6.3 kernel versions.
> linux 6.3 compat changes for truenas/zfs-2.2-release

- etc/Makefile.am
- etc/rc.d/Makefile.am
After updating to zfs-2.2, zfsd does not start at boot on Core due to executable permissions missing. 
Through core-build and by verifying that zfsd runs at startup
> NAS-122578 / None / Make zfsd executable in order to run it from the rc.d script

- config/kernel-inode-permission.m4
- include/os/linux/zfs/sys/zpl.h
- module/os/linux/zfs/policy.c
- module/os/linux/zfs/zfs_acl.c
- module/os/linux/zfs/zpl_file.c
- module/os/linux/zfs/zpl_xattr.c
The CI workflow was no longer compiling successfully after its container recently moved to Linux 6.3. This patch adds compatibility support for Linux kernel 6.3 for the truenas zfs-2.1 branch.
By testing build on 5.15, 6.1, and 6.3 kernel versions.
> linux 6.3 compat changes for truenas/zfs-2.1-release

- module/zfs/dmu_recv.c
- module/zfs/dnode.c
Ticket: https://ixsystems.atlassian.net/browse/NAS-122583
Unlike regular receive, raw receive require destination to have the same block structure as the source.  In case of dnode reclaim this triggers two special cases, requiring special handling:
- If dn_nlevels == 1, we can change the ibs, but dnode_set_blksz() should not dirty the data buffer if block size does not change, or durign receive dbuf_dirty_lightweight() will trigger assertion.
- If dn_nlevels > 1, we just can't change the ibs, dnode_set_blksz() would fail and receive_object would trigger assertion, so we should destroy and recreate the dnode from scratch.
Reviewed-by: Paul Dagnelie <pcd@delphix.com>
Closes #15039
> NAS-123123 / 22.12.4 / Fix raw receive with different indirect block size.

- module/zfs/dmu_recv.c
- module/zfs/dnode.c
Unlike regular receive, raw receive require destination to have the same block structure as the source.  In case of dnode reclaim this triggers two special cases, requiring special handling:
- If dn_nlevels == 1, we can change the ibs, but dnode_set_blksz() should not dirty the data buffer if block size does not change, or durign receive dbuf_dirty_lightweight() will trigger assertion.
- If dn_nlevels > 1, we just can't change the ibs, dnode_set_blksz() would fail and receive_object would trigger assertion, so we should destroy and recreate the dnode from scratch.
Reviewed-by: Paul Dagnelie <pcd@delphix.com>
Closes #15039
> NAS-123123 / None / Fix raw receive with different indirect block size.

- module/zfs/dmu_recv.c
- module/zfs/dnode.c
Unlike regular receive, raw receive require destination to have the same block structure as the source.  In case of dnode reclaim this triggers two special cases, requiring special handling:
- If dn_nlevels == 1, we can change the ibs, but dnode_set_blksz() should not dirty the data buffer if block size does not change, or durign receive dbuf_dirty_lightweight() will trigger assertion.
- If dn_nlevels > 1, we just can't change the ibs, dnode_set_blksz() would fail and receive_object would trigger assertion, so we should destroy and recreate the dnode from scratch.
Reviewed-by: Paul Dagnelie <pcd@delphix.com>
Closes #15039
> NAS-123123 / 13.0 / Fix raw receive with different indirect block size.

- include/sys/vdev_impl.h
- module/zfs/vdev.c
- tests/zfs-tests/tests/functional/cli_root/zpool_attach/attach-o_ashift.ksh
- tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace-o_ashift.ksh
- tests/zfs-tests/tests/functional/cli_root/zpool_replace/replace_prop_ashift.ksh
Ashift can be set for a vdev only during its creation, and the top-level vdev does not change when a vdev is attached or replaced. The ashift property should not be used during attachment, as it does not allow attaching/replacing a vdev if the pool's ashift property is increased after the existing vdev was created. Instead, we should be able to attach the vdev if the attached vdev can satisfy the ashift requirement with its parent.
Signed-off-by: Ameer Hamza <ahamza@ixsystems.com>
Closes #15061
> [2.1] Ignore pool ashift property during vdev attachment

- include/sys/spa_impl.h
- module/zfs/spa_misc.c
- module/zfs/vdev.c
- module/zfs/zio.c
Since spa_min_alloc may not be a power of 2, unlike ashifts, in the case of DRAID, we should not select the minimal value among several vdevs. Rounding to a multiple of it is unlikely to work for other vdevs. Instead, using the greatest common divisor produces smaller yet more reasonable results.
Signed-off-by: Ameer Hamza <ahamza@ixsystems.com>
Closes #15067
> [2.1] spa_min_alloc should be GCD, not min

- contrib/debian/openzfs-zfs-test.install
- contrib/debian/openzfs-zfsutils.install
For native Debian packages, `zinject` and it's man page is packaged in ZFS test package. `zinject` is not not directly related to ZTS and should be packaged with other utilities, like it is already present in `zfs_<ver>.rpm/deb` packages. This can be particularly useful where we want to use `zinject` but don't want to install ZTS on the system.
This commit moves `zinject` binary and man page from `openzfs-zfs-test` to `openzfs-zfsutils` package.
Tested by building and installing native Debian packages.
> NAS-123369 / 23.10 / Packaging: Move zinject from openzfs-zfs-test to openzfs-zfsutils package

- contrib/debian/openzfs-zfs-test.install
- contrib/debian/openzfs-zfsutils.install
For native Debian packages, `zinject` and it's man page is packaged in ZFS test package. `zinject` is not not directly related to ZTS and should be packaged with other utilities, like it is already present in `zfs_<ver>.rpm/deb` packages. This can be particularly useful where we want to use `zinject` but don't want to install ZTS on the system.
This commit moves `zinject` binary and man page from `openzfs-zfs-test` to `openzfs-zfsutils` package.
Tested by building and installing native Debian packages.
> NAS-123369 / 24.04 / Packaging: Move zinject from openzfs-zfs-test to openzfs-zfsutils package

- module/zfs/zfs_vnops.c
Sync with upstream zfs-2.2-release branch
- CI Testing
- Scale Build: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/592/
> sync with upstream zfs-2.2-release branch

- cmd/zfs/zfs_main.c
- contrib/debian/rules.in
- etc/systemd/system/50-zfs.preset
- etc/systemd/system/zfs-share.service.in
- lib/libshare/os/freebsd/nfs.c
- lib/libshare/os/linux/nfs.c
- lib/libzfs/libzfs_changelist.c
- tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_006_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_008_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_mount/zfs_mount_012_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_set/mountpoint_002_pos.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_set/zfs_set_003_neg.ksh
There are some inconsistencies in the handling of `mountpoint`, `sharesmb` and `sharenfs`
properties.
If `mountpoint` property is set when dataset is unmounted, this would update the `mountpoint`
property. The mountpoint could be valid or invalid in this case. Setting the `mountpoint` property
would result in success and dataset would still be unmounted here.
On the other hand, if dataset is mounted and `mountpoint` property is updated to something
invalid where mount cannot be successful, for example, setting the mountpoint inside a readonly
directory. This would unmount the dataset, set the `mountpoint` property to requested value and
tries to mount the dataset. The mount operation returns error and this error is treated as overall
failure of setting the property while the property is …
> NAS-123279 / 23.10 / Improve the handling of mountpoint, sharesmb and sharenfs properties

- cmd/zpool/compatibility.d/grub2
GRUB opens the boot-pool in read-only mode, but not all read-only compatible zpool
features are listed in grub2 compatibility file.
GRUB opens the boot pool in read-only mode. All read-only compatible features for zpool
can be enabled and added to grub2 compatibility, as GRUB does not open the boot-pool
for write.
Tested by creating a boot-pool with all read-only compatible zpool features enabled and
booting from the boot-pool.
> NAS-124771 / 24.04 / Add all read-only compatible zpool features to grub2 compatibility

- cmd/zpool/compatibility.d/grub2
GRUB opens the boot-pool in read-only mode, but not all read-only compatible zpool
features are listed in grub2 compatibility file.
GRUB opens the boot pool in read-only mode. All read-only compatible features for zpool
can be enabled and added to grub2 compatibility, as GRUB does not open the boot-pool
for write.
Tested by creating a boot-pool with all read-only compatible zpool features enabled and
booting from the boot-pool.
> NAS-124771 / 23.10.1 / Add all read-only compatible zpool features to grub2 compatibility

- cmd/zpool/compatibility.d/grub2
Recently, all read-only compatible zpool features were added to `grub2` compatibility list. `obsolete_counts` is a read-only feature that depends on `device_removal` feature which is not read-only and is marked as `ZFEATURE_FLAG_MOS`. Creating a pool with `grub2` compatibility enables `device_removal` feature as well, which is not desired.
This commit removes the `obsolete_counts` feature from grub2 compatibility list, as GRUB only supports read-only compatible features.
Created a pool with grub2 compatibility, and checked on `obsolete_counts` and `device_removal` features. Before removing `obsolete_counts`, `device_removal` was also getting enabled, while not present in `grub2` compatibility list.
> NAS-124771 / 23.10.1 / Remove obsolete_counts from grub2 compatibility list

- cmd/zpool/compatibility.d/grub2
Recently, all read-only compatible zpool features were added to `grub2` compatibility list. `obsolete_counts` is a read-only feature that depends on `device_removal` feature which is not read-only and is marked as `ZFEATURE_FLAG_MOS`. Creating a pool with `grub2` compatibility enables `device_removal` feature as well, which is not desired.
This commit removes the `obsolete_counts` feature from grub2 compatibility list, as GRUB only supports read-only compatible features.
Created a pool with grub2 compatibility, and checked on `obsolete_counts` and `device_removal` features. Before removing `obsolete_counts`, `device_removal` was also getting enabled, while not present in `grub2` compatibility list.
> NAS-124771 / 24.04 / Remove obsolete_counts from grub2 compatibility list

- module/os/linux/zfs/policy.c
This commit fixes a bug whereby owner@ ACL that limits WRITE_DATA access for the owner of a file was not being properly enforced. The owner of a file should be prevented from write access in this case, but being owner of file should still allow the file owner to chmod, chown, and setacl.
> NAS-125208 / None / Remove inode_owner_or_capable override for secpolicy

- man/man4/zfs.4
- module/os/linux/zfs/arc_os.c
Commits 518b487 and 23bdb07 changed the default ARC size limit on Linux systems to 1/2 of physical memory, which has become too strict for modern systems with large amounts of RAM. This patch changes the default limit to match that of FreeBSD, so ZFS may have a unified value on both platforms.
Reviewed-by: George Melikov <mail@gmelikov.ru>
Signed-off-by: Edmund Nadolski <edmund.nadolski@ixsystems.com>
Closes #15437
> arc_default_max on Linux should match FreeBSD

- module/os/linux/zfs/policy.c
This commit fixes a bug whereby owner@ ACL that limits WRITE_DATA access for the owner of a file was not being properly enforced. The owner of a file should be prevented from write access in this case, but being owner of file should still allow the file owner to chmod, chown, and setacl.
> NAS-125208 / 23.10.1 / Remove inode_owner_or_capable override for secpolicy (#178)

- META
- contrib/debian/changelog
- contrib/truenas/changelog
- copy-builtin
- module/zfs/dnode.c
- module/zfs/vdev_trim.c
Sync with the upstream 2.1.14 release. Core 13.0-U6.1 is going to be updated to this.
- Clean Build
- CI Tests
- Bluefin and Core builds are waiting in queue, will merge after testing with them.
> Merge zfs-2.1.14

- META
- README.md
- cmd/zdb/zdb.c
- config/kernel-inode-times.m4
- include/Makefile.am
- include/os/freebsd/spl/sys/vfs.h
- include/os/freebsd/spl/sys/vnode.h
- include/sys/brt_impl.h
- include/sys/dmu.h
- man/man8/zdb.8
- module/os/freebsd/spl/spl_vfs.c
- module/os/freebsd/spl/spl_zlib.c
- module/os/freebsd/zfs/event_os.c
- module/os/freebsd/zfs/zfs_ctldir.c
- module/os/freebsd/zfs/zfs_vnops_os.c
- module/zfs/brt.c
- module/zfs/dbuf.c
- module/zfs/dmu.c
- module/zfs/dnode.c
- module/zfs/zfs_vnops.c
- module/zfs/zil.c
- module/zfs/zio.c
- rpm/generic/zfs-dkms.spec.in
- tests/zfs-tests/tests/functional/cli_root/zdb/zdb_args_neg.ksh
- tests/zfs-tests/tests/functional/cli_root/zfs_load-key/zfs_load-key_common.kshlib
Sync with the upstream zfs-2.2.2 after fixes related to block cloning. Also cherry-picked https://github.com/truenas/zfs/pull/189/commits/443a2f2fed05f2291bf5d41bc48347072db38e7d.
- Clean Build
- CI Tests
- Cobia build in progress: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/665/, will merge after successful build and sanity testing.
> Merge zfs-2.2.2

- module/zfs/zil.c
To improve 128KB block write performance in case of multiple VDEVs ZIL used to spit those writes into two 64KB ones.  Unfortunately it was found to cause LWB buffer overflow, trying to write maximum- sizes 128KB TX_CLONE_RANGE record with 1022 block pointers into 68KB buffer, since unlike TX_WRITE ZIL code can't split it.
This is a minimally-invasive temporary block cloning fix until the following more invasive prediction code refactoring.
- Clean build on for stable/cobia: https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/669/parameters/
- Following test on Scale:
```
echo 1 > /sys/module/zfs/parameters/zfs_bclone_enabled
mkdir -p /var/tmp/disk-bclone …
```
> ZIL: Remove 128K into 2x68K LWB split optimization

- module/os/freebsd/zfs/zfs_vfsops.c
- module/os/linux/zfs/zpl_file_range.c
- module/zfs/zil.c
1. To improve 128KB block write performance in case of multiple VDEVs ZIL used to spit those writes into two 64KB ones.  Unfortunately it was found to cause LWB buffer overflow, trying to write maximum- sizes 128KB TX_CLONE_RANGE record with 1022 block pointers into 68KB buffer, since unlike TX_WRITE ZIL code can't split it. This is a minimally-invasive temporary block cloning fix until the following more invasive prediction code refactoring.
2. Re-enable Block cloning for dragonfish nightlies
- Build for dragonfish (in progress): https://ci.tn.ixsystems.net/jenkins/job/TrueNAS%20SCALE%20-%20Unstable/job/Build%20-%20TrueNAS%20SCALE_Custom/670/
- CI tests
> [stable/dragonfish] ZIL block cloning fix & re-enable block cloning

- include/os/freebsd/spl/sys/debug.h
- include/os/linux/spl/sys/debug.h
- lib/libspl/include/assert.h
- module/zfs/dbuf.c
This pull request includes recent block cloning fixes by @amotin. Details are mentioned in individual commits.
- CI testing
> [release/23.10.1] Block Cloning Fixes
